import { useEffect, useState } from 'react';
import type { PersistedState, VaultData } from '../../shared/types';

export function Eip7702({ state, vault, action, setView }: { state: PersistedState; vault: VaultData | null; action: any; setView: any }) {
  const [delegate, setDelegate] = useState(import.meta.env.VITE_CATSHIT_DELEGATE_ADDRESS || '0x0000000000000000000000000000000000000000');
  const [status, setStatus] = useState<any>(null);
  const [txHash, setTxHash] = useState<string | null>(state.latestDelegationTxHash || null);
  const [error, setError] = useState<string | null>(null);
  useEffect(() => { action('wallet:getDelegation').then((res:any)=>setStatus(res)).catch((e:any)=>setError(e.message)); }, [state.settings.activeChainId]);
  return <div className="col"><div className="card light"><div className="page-top"><button className="back-link clickable" onClick={()=>setView('settings')}>← Back</button><div className="title medium">CATSHIT Mint Setup</div></div><div className="warning-inline">EIP-7702 delegation gives a delegate contract special execution authority. Only continue if you trust this setup.</div><div className="list" style={{marginTop:10}}><div className="review-row"><span>Wallet</span><strong className="mono break-all">{vault?.accounts[state.activeAccountIndex]?.address}</strong></div><div className="review-row"><span>Chain</span><strong>{state.settings.activeChainId}</strong></div><div className="review-row"><span>Status</span><strong>{status?.state || 'loading'}</strong></div><div className="review-row"><span>Delegated to</span><strong className="mono break-all">{status?.delegate || '—'}</strong></div><input className="input mono" value={delegate} onChange={(e)=>setDelegate(e.target.value)} /></div><div className="footer-actions"><button className="btn secondary clickable" onClick={async()=>{const res=await action('wallet:signDelegation',{delegate}); alert(JSON.stringify(res.result,null,2));}}>Sign authorization</button><button className="btn primary clickable" onClick={async()=>{const res=await action('wallet:activateDelegation',{delegate}); setTxHash(res.hash);}}>Activate delegation</button><button className="btn light clickable" onClick={async()=>{const res=await action('wallet:revokeDelegation'); setTxHash(res.hash);}}>Revoke</button></div>{txHash ? <div className="mono success" style={{marginTop:10}}>latest tx: {txHash}</div> : null}{error ? <div className="inline-note danger-box">{error}</div> : null}</div></div>;
}
